<a href="https://colab.research.google.com/github/Francis-30/Francis-30/blob/main/churn_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import plotly.express as px

In [ ]:
path = '/content/drive/MyDrive/Churn_Modelling.csv'

In [ ]:
churn_df = pd.read_csv(path)
churn_df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [ ]:
churn_df.tail(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
churn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [12]:
churn_df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [25]:
churn_df.drop_duplicates()

,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,France,Female,42,2,0.00,1,1,1,101348.88,1
1,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,France,Female,39,1,0.00,2,0,0,93826.63,0
4,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...
9995,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [20]:
churn_df.Geography.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

Exited means customer no longer use the bank
**bold text**

In [21]:
data = churn_df.groupby(['Geography','Exited'])['Exited'].count().reset_index(name = 'count')
data

  Geography  Exited  count
0    France       0   4204
1    France       1    810
2   Germany       0   1695
3   Germany       1    814
4     Spain       0   2064
5     Spain       1    413

In [23]:
fig = px.bar(data, x='Geography', y='count', color='Exited')
fig.show()

In [26]:
churn_df.Exited.unique()

array([1, 0])

In [27]:
churn_df['status']=churn_df.Exited.replace(1,'Exited').replace(0,'Retained')

In [28]:
churn_df.head(10)

,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,status
0,France,Female,42,2,0.00,1,1,1,101348.88,1,Exited
1,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,Retained
2,France,Female,42,8,159660.80,3,1,0,113931.57,1,Exited
3,France,Female,39,1,0.00,2,0,0,93826.63,0,Retained
4,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,Retained
5,Spain,Male,44,8,113755.78,2,1,0,149756.71,1,Exited
6,France,Male,50,7,0.00,2,1,1,10062.80,0,Retained
7,Germany,Female,29,4,115046.74,4,1,0,119346.88,1,Exited
8,France,Male,44,4,142051.07,2,0,1,74940.50,0,Retained
9,France,Male,27,2,134603.88,1,1,1,71725.73,0,Retained

In [29]:
churn_df.status.unique()

array(['Exited', 'Retained'], dtype=object)

In [30]:
data = churn_df.groupby(['Geography','status'])['status'].count().reset_index(name='count')
data

  Geography    status  count
0    France    Exited    810
1    France  Retained   4204
2   Germany    Exited    814
3   Germany  Retained   1695
4     Spain    Exited    413
5     Spain  Retained   2064

In [31]:
fig = px.bar(data, x='Geography', y='count', color='status')
fig.show()

In [32]:
data= churn_df.groupby(['Geography'])['status'].value_counts(normalize= True).reset_index(name='percentage')
data

  Geography    status  percentage
0    France  Retained    0.838452
1    France    Exited    0.161548
2   Germany  Retained    0.675568
3   Germany    Exited    0.324432
4     Spain  Retained    0.833266
5     Spain    Exited    0.166734

In [33]:
fig = px.bar(data, x='Geography', y ='percentage', color = 'status')
fig.show()

In [34]:
data = churn_df.groupby('status')['status'].count().reset_index(name='count')
data

     status  count
0    Exited   2037
1  Retained   7963

In [35]:
data = churn_df.groupby('status')['status'].count().reset_index(name='count')
data

     status  count
0    Exited   2037
1  Retained   7963

In [36]:
fig = px.pie(data, values='count', labels='status')
fig.show()

In [37]:
churn_df.Gender.unique()

array(['Female', 'Male'], dtype=object)

In [38]:
data = churn_df.groupby(['Gender','status'])['status'].count().reset_index(name='count')
data

   Gender    status  count
0  Female    Exited   1139
1  Female  Retained   3404
2    Male    Exited    898
3    Male  Retained   4559

In [39]:
fig = px.bar(data, x='Gender', y='count', color='status')
fig.show()

In [40]:
churn_df.Age.unique()

array([42, 41, 39, 43, 44, 50, 29, 27, 31, 24, 34, 25, 35, 45, 58, 32, 38,
       46, 36, 33, 40, 51, 61, 49, 37, 19, 66, 56, 26, 21, 55, 75, 22, 30,
       28, 65, 48, 52, 57, 73, 47, 54, 72, 20, 67, 79, 62, 53, 80, 59, 68,
       23, 60, 70, 63, 64, 18, 82, 69, 74, 71, 76, 77, 88, 85, 84, 78, 81,
       92, 83])

In [41]:
 churn_df.Tenure.unique()

array([ 2,  1,  8,  7,  4,  6,  3, 10,  5,  9,  0])

In [42]:
Tenure = churn_df.groupby(['Tenure','status'])['status'].count().reset_index(name='count')
Tenure

    Tenure    status  count
0        0    Exited     95
1        0  Retained    318
2        1    Exited    232
3        1  Retained    803
4        2    Exited    201
5        2  Retained    847
6        3    Exited    213
7        3  Retained    796
8        4    Exited    203
9        4  Retained    786
10       5    Exited    209
11       5  Retained    803
12       6    Exited    196
13       6  Retained    771
14       7    Exited    177
15       7  Retained    851
16       8    Exited    197
17       8  Retained    828
18       9    Exited    213
19       9  Retained    771
20      10    Exited    101
21      10  Retained    389

In [43]:
fig= px.bar(Tenure, x='Tenure', y='count',color='status')
fig.show()

In [44]:
Tenure =churn_df.groupby(['Tenure'])['status'].value_counts(normalize = True).reset_index(name ='percentage')
Tenure

    Tenure    status  percentage
0        0  Retained    0.769976
1        0    Exited    0.230024
2        1  Retained    0.775845
3        1    Exited    0.224155
4        2  Retained    0.808206
5        2    Exited    0.191794
6        3  Retained    0.788900
7        3    Exited    0.211100
8        4  Retained    0.794742
9        4    Exited    0.205258
10       5  Retained    0.793478
11       5    Exited    0.206522
12       6  Retained    0.797311
13       6    Exited    0.202689
14       7  Retained    0.827821
15       7    Exited    0.172179
16       8  Retained    0.807805
17       8    Exited    0.192195
18       9  Retained    0.783537
19       9    Exited    0.216463
20      10  Retained    0.793878
21      10    Exited    0.206122

In [47]:
fig= px.bar(Tenure, x='Tenure', y ='percentage', color='status')
fig.show()